name: 'editorconfig-checker'
description: 'Using editorconfig-checker/editorconfig-checker to verify your files'
outputs:
  output:
    description: 'validation results'
runs:
  using: 'docker'
  image: 'Dockerfile'
